name: context-harvest
on:
  schedule: [{ cron: "23 3 * * *" }]
  workflow_dispatch: {}
jobs:
  harvest:
    runs-on: ubuntu-latest
    env:
      SUBSCRIPTION_ID: cf96f9c0-5e5e-43d8-8ded-ae5ca7c23380
      RESOURCE_GROUP: rg-adf-dbx-demo
      ADF_FACTORY: adf-taxi-sono-global
      STORAGE_ACCOUNT: sttaxistorage
      DATABRICKS_HOST: https://adb-930731835834472.12.azuredatabricks.net
    steps:
      - uses: actions/checkout@v4

      - name: Verify scripts present
        run: |
          test -f scripts/ctx_azure.sh || { echo "scripts/ctx_azure.sh missing"; exit 1; }
          test -f scripts/ctx_databricks.sh || { echo "scripts/ctx_databricks.sh missing"; exit 1; }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install CLIs
        run: |
          python -m pip install --upgrade databricks-cli
          # Azure CLI is pre-installed on GitHub runners
          az version
          az extension add -n datafactory --only-show-errors || az extension update -n datafactory --only-show-errors
          az extension add -n resource-graph --only-show-errors || az extension update -n resource-graph --only-show-errors

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Databricks auth
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<EOF
          $DATABRICKS_HOST
          $DATABRICKS_TOKEN
          EOF

      - name: Harvest Azure
        run: bash scripts/ctx_azure.sh

      - name: Harvest Databricks
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: bash scripts/ctx_databricks.sh

      - name: Commit snapshots
        run: |
          git config user.name  "context-bot"
          git config user.email "context-bot@users.noreply.github.com"
          git add adf-dbx-delta/.context || true
          git diff --cached --quiet || git commit -m "context: refresh snapshots"
          git push

