name: deploy
on:
  push:
    branches: [main]
    paths:
      - 'adf-dbx-delta/notebooks/**'
      - 'ARMTemplateForFactory.json'
      - 'ARMTemplateParametersForFactory.json'
  workflow_dispatch: {}

jobs:
  deploy-adf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy ADF ARM Template
        run: |
          az deployment group create \
            --resource-group rg-adf-dbx-demo \
            --template-file ARMTemplateForFactory.json \
            --parameters @ARMTemplateParametersForFactory.json
            
  deploy-databricks:
    runs-on: ubuntu-latest
    needs: deploy-adf
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
        
      - name: Install Databricks CLI
        run: python -m pip install --upgrade databricks-cli
        
      - name: Configure Databricks
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<EOF
          https://adb-930731835834472.12.azuredatabricks.net
          $DATABRICKS_TOKEN
          EOF
          
      - name: Upload Notebooks
        run: |
          databricks workspace import \
            --language PYTHON \
            --format SOURCE \
            --overwrite \
            adf-dbx-delta/notebooks/bronze_silver.py \
            /Shared/bronze_silver