name: deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'bronze_silver.ipynb'
      - 'adf-dbx-delta/notebooks/bronze_silver.py'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: https://adb-930731835834472.12.azuredatabricks.net
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade databricks-cli

      - name: Databricks auth
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<EOF
          $DATABRICKS_HOST
          $DATABRICKS_TOKEN
          EOF

      - name: Import notebook to /Shared (Python source)
        run: |
          databricks workspace import \
            --language PYTHON --format SOURCE --overwrite \
            adf-dbx-delta/notebooks/bronze_silver.py \
            /Shared/bronze_silver

      - name: Verify import
        run: databricks workspace list /Shared || true
